#!/bin/bash
#SBATCH -A sc5fp4p
#SBATCH -J auto-particle-mpi-large
#SBATCH -o auto-particle-mpi-large.stdout
#SBATCH -N 1 -n 8         
#SBATCH -p RM
#SBATCH -t 00:10:00     


export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=0

rm mpi_sum.txt

mpirun -np 1 ./serial -n 10000 -no -s mpi_sum.txt
mpirun -np 1 ./mpi -n 10000 -no -s mpi_sum.txt
mpirun -np 2 ./mpi -n 10000 -no -s mpi_sum.txt
mpirun -np 4 ./mpi -n 10000 -no -s mpi_sum.txt
mpirun -np 8 ./mpi -n 10000 -no -s mpi_sum.txt
mpirun -np 2 ./mpi -n 20000 -no -s mpi_sum.txt
mpirun -np 4 ./mpi -n 40000 -no -s mpi_sum.txt
mpirun -np 8 ./mpi -n 80000 -no -s mpi_sum.txt
mpirun -np 1 ./autograder -v mpi -s mpi_sum.txt
