#!/bin/bash
#SBATCH -A sc5fp4p 
#SBATCH -J auto-particle-openmp-large
#SBATCH -o auto-particle-openmp-large.stdout
#SBATCH -n 8         
#SBATCH -p RM
#SBATCH -t 00:10:00     
#SBATCH -N 1        

rm openmp_sum.txt
./serial -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=1
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 10000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 20000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 40000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 80000 -no -s openmp_sum.txt
./autograder -v openmp -s openmp_sum.txt
