#!/bin/bash
#SBATCH -A sc5fp4p 
#SBATCH -J auto-particle-omp-small
#SBATCH -o auto-particle-omp-small.stdout
#SBATCH -n 8         
#SBATCH -p RM
#SBATCH -t 00:10:00     
#SBATCH -N 1        

rm openmp_sum.txt
./serial -n 2000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=1
./openmp -n 2000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 2000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 2000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 2000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=2
./openmp -n 4000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=4
./openmp -n 8000 -no -s openmp_sum.txt
export OMP_NUM_THREADS=8
./openmp -n 16000 -no -s openmp_sum.txt
./autograder -v openmp -s openmp_sum.txt
