#!/bin/bash
#SBATCH -A sc5fp4p
#SBATCH -J particle-openmp8
#SBATCH -o particle-openmp8.stdout
#SBATCH -n 8         
#SBATCH -p RM
#SBATCH -t 00:10:00     
export OMP_NUM_THREADS=8
./openmp -n 5000 -o openmp.txt
